spring:
  application:
    name: zipkin
  datasource:
    url: jdbc:mysql://localhost:3306/opentracing
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
   storage:
      type: mysql
server:
  port: 8080
